### ISSUE TITLE
Implement artisan command

### ISSUE THREAD

**Issue by bilfeldt** [bilfeldt/laravel-route-statistics#1]
Implement an artisan command for showing route statistics in a table view

- [Option array](https://laravel.com/docs/master/artisan#option-arrays) for `group` (example: `--group=user --group=date`)
- Option for filtering by `user` (`--user=123`)
- Option for filtering by `team` (`--team=123`)
- Option for filtering by `method` (`--method=GET`)
- Option for filtering by `route` (`--route='api.example'`)
- Option for filtering by `code` (`--code=200` note that it would be nice to accept a syntax like `--code=2xx' or '--code=2%')
- Option for filtering by `ip` (`--ip='192.168.0.102'` note that it would be nice to accept a syntax like `--ip=192.168.0.*' or '--ip=192.168.%')
- Option for filtering by `date` (`--date=2021-01-22` should return everything on that day - how to select the *level*, from config or another option?)
- Option for amount of returned results (default =20)

**Comment by JackWH** [comment]
Hey @bilfeldt, great package — looking forward to implementing it soon.

Just a thought that might be worth including in this issue... It would be a really useful addition if the proposed Artisan command(s) could also list all routes which have _not_ been logged.

This way, the package could act as a sort of [tombstoning](https://phpscaling.com/2017/08/28/code-tombstones/) service for routes. I'm sure many larger applications have old routes left behind, with legacy code to support them. It would make it easy to identify leftover code and clean it up.

You could use the `php artisan route:list` command, in combination with some of the formatting/filtering flags, to identify all available routes — then reduce the list down to just those that haven't been logged by the package.

**Comment by bilfeldt** [comment]
> Hey @bilfeldt, great package — looking forward to implementing it soon.
> 
> Just a thought that might be worth including in this issue... It would be a really useful addition if the proposed Artisan command(s) could also list all routes which have _not_ been logged.
> 
> This way, the package could act as a sort of automatic [tombstoning](https://phpscaling.com/2017/08/28/code-tombstones/) service for routes. I'm sure many larger applications have old routes left behind, with legacy code to support them. It would make it easy to identify leftover code and clean it up.
> 
> You could use the `php artisan route:list` command, in combination with some of the formatting/filtering flags, to identify all available routes — then reduce the list down to just those that haven't been logged by the package.
> 
> Hopefully this might be simple enough to include, but if you need any help, I can try and put together a PR when time permits.

@JackWH What a great idea 👍  Have created a separate issue for it (#9) feel free to submit a PR if you feel like it, otherwise I will have a look at it when I have the time.
