### ISSUE TITLE
Not possible to use the package in Laravel 10 with PHP 8.1?

### ISSUE THREAD

**Issue by MuriloChianfa** [bilfeldt/laravel-route-statistics#21]
### Subject of the issue

Im try to download the package in my project and none of the versios of i have tryied works.

### Your environment

![image](https://github.com/bilfeldt/laravel-route-statistics/assets/60560085/df650322-6829-49c4-9a37-56e45867a591)

### Steps to reproduce

Trying to install the latest version of the package:
![image](https://github.com/bilfeldt/laravel-route-statistics/assets/60560085/aa777693-0245-4893-acd7-5f3aa0a5bbeb)

And the version recommended for PHP 8.1 in readme:
![image](https://github.com/bilfeldt/laravel-route-statistics/assets/60560085/7817a3c4-1ff9-412e-b8b7-7d428dfdd452)

> Notice that not works for Laravel 10 using PHP 8.1 version.

### Expected behaviour

Is expected to work in Laravel 10 with PHP 8.1 as described by Laravel 10:
![image](https://github.com/bilfeldt/laravel-route-statistics/assets/60560085/7da3b8c0-0107-4dbd-aa8d-e5b9a309c930)

### Actual behaviour

Having conflicts for this combination of versions.
I think it's easy to solve, because for the combination of Laravel 10 with PHP 8.2 it already works.

**Comment by bilfeldt** [comment]
@MuriloChianfa the supported PHP version of this package is 8.2 and is not fixed with the supported PHP versions from Laravel.

That being said, I will consider if PHP 8.1 can be re-added as I can see you have submitted a PR for this #22

**Comment by bilfeldt** [comment]
Added in [`v2.2.0`](https://github.com/bilfeldt/laravel-route-statistics/releases/tag/v2.2.0)
