### ISSUE TITLE
PHP 8.3 Support needed

### ISSUE THREAD

**Issue by prof-usman** [bilfeldt/laravel-route-statistics#25]
**PHP8.3 Support**

When on PHP 8.3, it gives error

**Your environment**
Ubuntu 23, PHP 8.3

Problem 1
- bilfeldt/laravel-route-statistics is locked to version v3.0.0 and an update of this package was not requested.
- bilfeldt/laravel-route-statistics v3.0.0 requires php ~8.1.0 || ~8.2.0 -> your php version (8.3.1; overridden via config.platform, same as actual) does not satisfy that requirement

**Comment by bilfeldt** [comment]
PHP 8.3 support added in [v3.1.0](https://github.com/bilfeldt/laravel-route-statistics/releases/tag/v3.1.0)
