### ISSUE TITLE
Laravel 11 Support Needed

### ISSUE THREAD

**Issue by prof-usman** [bilfeldt/laravel-route-statistics#29]
### Laravel 11 Support Needed

bilfeldt/laravel-route-statistics v3.1.0 requires laravel/framework ^10.0 -> found laravel/framework[v10.0.0, ..., v10.48.2] but it conflicts with your root composer.json require (^11.0).

**Comment by bilfeldt** [comment]
@prof-usman upgrade to version [3.2.0](https://github.com/bilfeldt/laravel-route-statistics/releases/tag/v3.2.0)
