### ISSUE TITLE
PHP 8.4 unsupported

### ISSUE THREAD

**Issue by graydav1** [bilfeldt/laravel-route-statistics#42]
### Subject of the issue

Trying to install this onto Laravel Sail which uses PHP 8.4.1 at time of writing, but `composer.json` restricts it to 8.1, 8.2 and 8.3

### Your environment

PHP 8.4.1

### Steps to reproduce

Try and install the package while on a newly created Laravel Sail container which uses 8.4.1 at time of writing

### Expected behaviour

Installs properly

### Actual behaviour

Fails with "not satisfied by your platform" error

**Comment by bilfeldt** [comment]
Feel free to make a PR @graydav1 👍 I will have a look at this myself soon otherwise.
