### ISSUE TITLE
README: Enable global logging class RouteStatisticsMiddleware does not exist

### ISSUE THREAD

**Issue by RicardoRamirezR** [bilfeldt/laravel-route-statistics#7]
Hi @bilfeldt be aware that ```RouteStatisticsMiddleware``` does not exists while ```RouteStatistics``` does exists

**Comment by bilfeldt** [comment]
> Hi @bilfeldt be aware that `RouteStatisticsMiddleware` does not exists while `RouteStatistics` does exists

@RicardoRamirezR I am not sure what you mean exactly? The `RouteStatisticsMiddleware` does exist and can be located here: https://github.com/bilfeldt/laravel-route-statistics/blob/main/src/Http/Middleware/RouteStatisticsMiddleware.php

Note that this middleware has an [alias](https://github.com/bilfeldt/laravel-route-statistics/blob/998db00d8f2846edcf7dcbee86701415d968838e/src/LaravelRouteStatisticsServiceProvider.php#L78) `routestatistics`

**Comment by bilfeldt** [comment]
@RicardoRamirezR Does #8 solve the issue you were mentioning (opposite of original description as the docs mentioned the `RouteStatistics` middleware while the actual class name was `RouteStatisticsMiddleware`)?

**Comment by RicardoRamirezR** [comment]
Seems odd @bilfeldt I just installed you package for Laravel 7, and looking at ```bilfeldt/laravel-route-statistics/src/Http/Middleware/RouteStatistics.php```  

```php
<?php

namespace Bilfeldt\LaravelRouteStatistics\Http\Middleware;

use Closure;

class RouteStatistics
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $request->routeStatistics();

        return $next($request);
    }
}
```
